In [40]:
#Q1: EIGEN DECOMPOSTITION

In [41]:
   # A=q lembda Qt

In [42]:
A=[[2,5],[3,4]]
eigenvalue,eigenvector=np.linalg.eig(A)

In [43]:
print("eigenvalues",eigenvalue)
print()
print("eigenvector",eigenvector)

eigenvalues [-1.  7.]

eigenvector [[-0.85749293 -0.70710678]
 [ 0.51449576 -0.70710678]]


In [44]:
lembda=np.diag(eigenvalue)
lembda

array([[-1.,  0.],
       [ 0.,  7.]])

In [45]:
inv=np.linalg.inv(eigenvector)

In [46]:
A=eigenvector@lembda@inv
A


array([[2., 5.],
       [3., 4.]])

In [47]:
inv

array([[-0.72886899,  0.72886899],
       [-0.53033009, -0.88388348]])

In [48]:
eigenvector

array([[-0.85749293, -0.70710678],
       [ 0.51449576, -0.70710678]])

In [49]:
lembda

array([[-1.,  0.],
       [ 0.,  7.]])

In [50]:
x=lembda[0][0]*eigenvector[:,0:1]*inv[0]
print(x)

[[-0.625  0.625]
 [ 0.375 -0.375]]


In [51]:
def func(lembda,eigenvector,inv,i):
   return (lembda[i][i]*eigenvector[:,i:i+1])*inv[i]

In [52]:
sum=0
for i in  range(len(eigenvalue)):
    print(func(lembda,eigenvector,inv,i))
    sum=sum+func(lembda,eigenvector,inv,i)
print(sum)

[[-0.625  0.625]
 [ 0.375 -0.375]]
[[2.625 4.375]
 [2.625 4.375]]
[[2. 5.]
 [3. 4.]]
