<a href="https://colab.research.google.com/github/Zeenatwaseem/deep-learning-with-python/blob/main/Paddingandstridezeenat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import numpy

arr = numpy.array([[3, 3, 2, 1, 0], [0, 0, 1, 3, 1], [3, 1, 2, 2, 3],
                   [2, 0, 0, 2, 2], [2, 0, 0, 0, 1]])
print("The original matrix:")
print(arr)
p = [[0, 1, 2], [2, 2, 0], [0, 1, 2]]
K = 3
l = 3
for j in range(len(p)):

    K = 3
    for i in range(len(p)):

        print("A sliced submatrix:")
        print(np.sum((arr[j:l, i:K]) * p))

        K += 1
    #print(i, K)
    l += 1

The original matrix:
[[3 3 2 1 0]
 [0 0 1 3 1]
 [3 1 2 2 3]
 [2 0 0 2 2]
 [2 0 0 0 1]]
A sliced submatrix:
12
A sliced submatrix:
12
A sliced submatrix:
17
A sliced submatrix:
10
A sliced submatrix:
17
A sliced submatrix:
19
A sliced submatrix:
9
A sliced submatrix:
6
A sliced submatrix:
14


In [1]:
import numpy as np
import numpy

arr = numpy.array([[3, 3, 2, 1, 0], [0, 0, 1, 3, 1], [3, 1, 2, 2, 3],
                   [2, 0, 0, 2, 2], [2, 0, 0, 0, 1]])
print("The original matrix:")
print(arr)
p = [[0, 1, 2], [2, 2, 0], [0, 1, 2]]
K = len(p)
l = len(p)
list1=[]
for j in range(len(p)):

    K = 3
    list=[]
    for i in range(len(p)):

       # print("A sliced submatrix:")
        list.append(np.sum((arr[j:l, i:K]) * p))

        K += 1
    #print(i, K)
    l += 1

    list1.append(list)

list1=[x for x in list1 if x]
l=np.array (list1)
print()
print("after scaling")
print(l)

The original matrix:
[[3 3 2 1 0]
 [0 0 1 3 1]
 [3 1 2 2 3]
 [2 0 0 2 2]
 [2 0 0 0 1]]

after scaling
[[12 12 17]
 [10 17 19]
 [ 9  6 14]]


In [ ]:
import numpy as np
import numpy

arr =np.array([[3, 3, 2, 1, 0], [0, 0, 1, 3, 1], [3, 1, 2, 2, 3],




        [2, 0, 0, 2, 2], [2, 0, 0, 0,1]])
arr=np.pad(arr, [(1,1), (1,1)], mode='constant')



print("The original matrix after padding:")
print(arr)
p = [[0, 1, 2], [2, 2, 0], [0, 1, 2]]
K = len(p)
l = len(p)
list1=[]
for j in range(len(arr)):
    list=[]
    K = len(p)
    for i in range(len(arr[0])):

        

        if (np.shape(arr[j:l, i:K]))==np.shape(p):
            #print(np.sum((arr[j:l, i:K])*p))
            list.append(np.sum((arr[j:l, i:K])*p))

        K += 1
    #print(i, K)
    list1.append(list)
    l += 1
list1=[x for x in list1 if x]
l=np.array (list1)
print()
print("after scaling")
print(l)

The original matrix after padding:
[[0 0 0 0 0 0 0]
 [0 3 3 2 1 0 0]
 [0 0 0 1 3 1 0]
 [0 3 1 2 2 3 0]
 [0 2 0 0 2 2 0]
 [0 2 0 0 0 1 0]
 [0 0 0 0 0 0 0]]

after scaling
[[ 6 14 17 11  3]
 [14 12 12 17 11]
 [ 8 10 17 19 13]
 [11  9  6 14 12]
 [ 6  4  4  6  4]]


In [3]:

import numpy as np
import numpy

arr =np.array([[3, 3, 2, 1, 0], [0, 0, 1, 3, 1], [3, 1, 2, 2, 3],




        [2, 0, 0, 2, 2], [2, 0, 0, 0,1]])
arr=np.pad(arr, [(1,1), (1,1)], mode='constant')



print("The original matrix after padding:")
print(arr)
p = [[0, 1, 2], [2, 2, 0], [0, 1, 2]]
K = len(p)
l = len(p)
n=int(input("enter stride"))
list1=[]
for j in range(0,len(arr)-1,n):
    list=[]
    K = len(p)
    for i in range(0,len(arr[0])-1,n):

        

        if (np.shape(arr[j:l, i:K]))==np.shape(p):
            #print(arr[j:l, i:K])
            list.append(np.sum((arr[j:l, i:K])*p))

        K += n
    #print(i, K)
    list1.append(list)
    l += n
list1=[x for x in list1 if x]
l=np.array (list1)
print()
print("after scaling wth stride of of n for ex as 2")
print(l)

The original matrix after padding:
[[0 0 0 0 0 0 0]
 [0 3 3 2 1 0 0]
 [0 0 0 1 3 1 0]
 [0 3 1 2 2 3 0]
 [0 2 0 0 2 2 0]
 [0 2 0 0 0 1 0]
 [0 0 0 0 0 0 0]]
enter stride1

after scaling wth stride of of n for ex as 2
[[ 6 14 17 11  3]
 [14 12 12 17 11]
 [ 8 10 17 19 13]
 [11  9  6 14 12]
 [ 6  4  4  6  4]]
