In [1]:
import numpy as np
data = [[5.1, 3.5, 1.4, 0.2],
        [4.9, 3.0, 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        
        ]

from numpy.linalg import eig

In [2]:
from re import fullmatch
from sklearn.decomposition import PCA
pca = PCA(n_components = 4)
fit = pca.fit(data)
print(fit.components_)

[[ 0.72004239  0.6908134  -0.06569485  0.        ]
 [ 0.69268617 -0.72118945  0.00846438  0.        ]
 [-0.04153113 -0.05160062 -0.99780386 -0.        ]
 [ 0.          0.          0.          1.        ]]


In [3]:
odata = np.copy(np.array(data))
print(np.array(data))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


In [4]:
for j in range(len(data[0])):
    sum = 0
    for i in range(len(data)):
        sum += data[i][j]
    for i in range(len(data)):
        data[i][j] -= sum/len(data)
print(np.array(data))


[[ 2.7500000e-01  3.0000000e-01  0.0000000e+00  0.0000000e+00]
 [ 7.5000000e-02 -2.0000000e-01  0.0000000e+00  0.0000000e+00]
 [-1.2500000e-01  4.4408921e-16 -1.0000000e-01  0.0000000e+00]
 [-2.2500000e-01 -1.0000000e-01  1.0000000e-01  0.0000000e+00]]


In [5]:
data = np.array(data)
covdata = np.cov(data.T)
print(covdata)

[[ 0.04916667  0.03       -0.00333333  0.        ]
 [ 0.03        0.04666667 -0.00333333  0.        ]
 [-0.00333333 -0.00333333  0.00666667  0.        ]
 [ 0.          0.          0.          0.        ]]


In [6]:
values, vectors = np.linalg.eig(covdata)
print(values)
print()
print(vectors)

[0.07825299 0.01789147 0.00635554 0.        ]

[[ 0.72004239  0.69268617  0.04153113  0.        ]
 [ 0.6908134  -0.72118945  0.05160062  0.        ]
 [-0.06569485  0.00846438  0.99780386  0.        ]
 [ 0.          0.          0.          1.        ]]


In [7]:
var = []
for i in range(len(values)):
    var.append(values[i] / np.sum(values))
print(var)

[0.7634437922688404, 0.17455089817308628, 0.06200530955807335, 0.0]


In [8]:

k = 2
s = np.argsort(np.array(var)) 
s = s[::-1]
s = s[0:k]
s = sorted(s)
ndata = []
odata = np.array(odata).T
for i in s:
    ndata.append(odata[i])
print("New data:")
print(np.array(ndata).T)

New data:
[[5.1 3.5]
 [4.9 3. ]
 [4.7 3.2]
 [4.6 3.1]]
