In [29]:
import numpy as np
from numpy.linalg import svd
from numpy.linalg import eigh
from numpy.linalg import norm

In [30]:
A=np.array([[3,2,2],[2,3,-2]])

In [31]:
u,sigma,v=svd(A)

In [32]:
print("u",u)
print()
print("v",v)
print()
print("sigma",np.diag(sigma))

u [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

v [[-7.07106781e-01 -7.07106781e-01 -6.47932334e-17]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]

sigma [[5. 0.]
 [0. 3.]]


In [33]:
res=u@np.diag(sigma)
res

array([[-3.53553391, -2.12132034],
       [-3.53553391,  2.12132034]])

In [34]:
col=np.array([[0],[0]])
res=np.append(res,col,axis=1)

In [35]:
print(res)

[[-3.53553391 -2.12132034  0.        ]
 [-3.53553391  2.12132034  0.        ]]


In [36]:
result=res@v
result

array([[ 3.,  2.,  2.],
       [ 2.,  3., -2.]])

In [37]:
#approximation using max
sigma_approx=np.zeros((2,2))



In [38]:
A@A.T

array([[17,  8],
       [ 8, 17]])

In [39]:
ev,V=eigh(A@A.T)

In [40]:
#Q1: EIGEN DECOMPOSTITION

In [41]:
   # A=q lembda Qt

In [42]:
A=[[2,5],[3,4]]
eigenvalue,eigenvector=np.linalg.eig(A)

In [43]:
print("eigenvalues",eigenvalue)
print()
print("eigenvector",eigenvector)

eigenvalues [-1.  7.]

eigenvector [[-0.85749293 -0.70710678]
 [ 0.51449576 -0.70710678]]


In [44]:
lembda=np.diag(eigenvalue)
lembda

array([[-1.,  0.],
       [ 0.,  7.]])

In [45]:
inv=np.linalg.inv(eigenvector)

In [46]:
A=eigenvector@lembda@inv
A


array([[2., 5.],
       [3., 4.]])

In [47]:
inv

array([[-0.72886899,  0.72886899],
       [-0.53033009, -0.88388348]])

In [48]:
eigenvector

array([[-0.85749293, -0.70710678],
       [ 0.51449576, -0.70710678]])

In [49]:
lembda

array([[-1.,  0.],
       [ 0.,  7.]])

In [50]:
x=lembda[0][0]*eigenvector[:,0:1]*inv[0]
print(x)

[[-0.625  0.625]
 [ 0.375 -0.375]]


In [51]:
def func(lembda,eigenvector,inv,i):
   return (lembda[i][i]*eigenvector[:,i:i+1])*inv[i]

In [52]:
sum=0
for i in  range(len(eigenvalue)):
    print(func(lembda,eigenvector,inv,i))
    sum=sum+func(lembda,eigenvector,inv,i)
print(sum)

[[-0.625  0.625]
 [ 0.375 -0.375]]
[[2.625 4.375]
 [2.625 4.375]]
[[2. 5.]
 [3. 4.]]
